language: scala
scala:
- 2.12.5
deploy:
  provider: heroku
  api_key:
    secure: GkvxZK/gWdvXpEbiIjg2rG10/6RXSyOvzKtyK26mYJLxDm9WTxDaEBZwqDc1GpG+/Iy9uJRj30yemK3Q/ZhrLyL6C/ZgwPjAEg3Y6EXIQ73XY5Io2mwJPV90OlTPB/qy/a7A3wb/0VB0t9gpkOSE7oKw1e59OoE5NByQFWgG6G9qscpDLjYSHEx/Dfyg4tvnbcacsezeGBnWofxpHERHZDAO0nQya9Jfukg1/N2xT0XusXWk/8pdggAVcEOGRDphBbE7TlC+i6jwmGEx+Pv703jPnkJu1WfiEAiaFm2h1B/GGqaLBvaL8jK8wgVUH1yq/U9+IFmRmhlIGXzLkpmHdvE2He3DunUDd3d9z1R4mGYm9QvJpmW6U81Y8WJRT/W1eZINqcKv2huNMy+FAEu3O3Qm4l9YWm4lxIm+sihDmG77wgCY0rmNSFa7xreI0duuLOehWuQmow7pUpsIxjphS9yX6q3CNZ36a43CXcsOJLysdyQXyVHyni2IEQ3QwpWBtxWl7JGX7l4jXr9VVWyQ8uvD6GNLVaLBo3BE7bno8PZ35Cy1lSJFKsIamEjwbxW4rX+OC7JX6T0AUQwfR47rptweh+7Y/SJWP0nE4NyBhK7TJPsp3mbIUrEnGVRycnuTK4op9Xbjwhf/hakp57JIy/af/zUoNJ0ldDBKw0pPb9E=
